# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# dissolve.py
# Created on: 2016-04-26 12:03:19.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: dissolve <input_data>
# Description:
# ---------------------------------------------------------------------------
#run this second no args
#C:\Python27\ArcGIS10.3\python.exe tra.py
# Import arcpy module
import arcpy
import json
import os


# Script arguments
input_data = arcpy.GetParameterAsText(0)

# Local variables:

#input data
path = "E:\\ncdeq\\DMS_RBRP.gdb"
temp_dissolve = "E:\\DMS_RBRP.gdb\\temp_dissolve"

#output data
outPathGDB = "E:\\ncdeq"
outGDB = "RDRBP_AGO.gdb"

uplift_Data = """[{
	"fieldName": "Hab_uplift_Restoration",
	"chartDescription": "Habitat Uplift Restoration",
	"chartType": "TRA",
	"chartLabel": "Uplift Restoration",
	"chartLevel": "3",
	"chartId": "22",
	"chartMatchId": "2"
}, {
	"fieldName": "Hab_uplift_AqCon",
	"chartDescription": "Habitat Uplift Aquatic Connectivity",
	"chartType": "TRA",
	"chartLabel": "Aquatic Connectivity",
	"chartLevel": "3",
	"chartId": "21",
	"chartMatchId": "2"
}, {
	"fieldName": "Hab_uplift_AdvConv",
	"chartDescription": "Habitat Uplift Avoided Conversion",
	"chartType": "TRA",
	"chartLabel": "Avoided Conversion",
	"chartLevel": "3",
	"chartId": "20",
	"chartMatchId": "2"
}, {
	"fieldName": "Hab_uplift_WetlandsBMPs",
	"chartDescription": "Habitat Wetlands and BMPs",
	"chartType": "TRA",
	"chartLabel": "Wetlands and BMPs",
	"chartLevel": "3",
	"chartId": "19",
	"chartMatchId": "2"
},{
	"fieldName": "WQ_uplift_norm",
	"chartDescription": "Total Water Quality Uplift",
	"chartType": "TRA",
	"chartLabel": "Water Quality",
	"chartLevel": "2",
	"chartId": "6",
	"chartMatchId": "1"
}, {
	"fieldName": "Hydro_uplift_norm",
	"chartDescription": "Total Hydrology Uplift",
	"chartType": "TRA",
	"chartLabel": "Hydrology",
	"chartLevel": "2",
	"chartId": "5",
	"chartMatchId": "1"
}, {
	"fieldName": "Hab_uplift_norm",
	"chartDescription": "Total Habitat Uplift",
	"chartType": "TRA",
	"chartLabel": "Habitat",
	"chartLevel": "2",
	"chartId": "2",
	"chartMatchId": "1"
}, {
	"fieldName": "ALL_uplift",
	"chartDescription": "Total Uplift",
	"chartType": "TRA",
	"chartLabel": "Total",
	"chartLevel": "1",
	"chartId": "1",
	"chartMatchId": "1"
}]"""

transposedTemplate =[{"fieldname": "ID","fieldType": "TEXT","Length":"150"},
					 {"fieldname": "geography_level","fieldType": "LONG","Length":""},
					 {"fieldname": "geography_match_id","fieldType": "TEXT","Length":"150"},
					 {"fieldname": "geography_label","fieldType": "TEXT","Length":"150"},
					 {"fieldname": "chart_id","fieldType": "LONG","Length":""},
					 {"fieldname": "chart_matchid","fieldType": "LONG","Length":""},
					 {"fieldname": "chart_level","fieldType": "LONG","Length":""},
					 {"fieldname": "chart_label","fieldType": "TEXT","Length":"255"},
					 {"fieldname": "chart_value","fieldType": "TEXT","Length":"255"},
					 {"fieldname": "chart_description","fieldType": "TEXT","Length":"150"},
					 {"fieldname": "chart_type","fieldType": "TEXT","Length":"150"},
					 {"fieldname": "chart_level_label","fieldType": "TEXT","Length":"150"}]

outGDBFull =  os.path.join(outPathGDB, outGDB)


#result data
transposed =  os.path.join(outGDBFull, 'ncdeq_normailized')

# arcpy.CreateTable_management(outGDBFull,'ncdeq_normailized')


for field in transposedTemplate:
	fieldName = field['fieldname']
	fieldType = field['fieldType']
	fieldLength = field['Length']
	arcpy.AddField_management(transposed, fieldName, fieldType, "", "", fieldLength, "", "NULLABLE", "NON_REQUIRED", "")

#add name fields for dissovled huc data where do I get that
#update the ago db. later

#check if field exists
def FieldExist(featureclass, fieldname):
	fieldList = arcpy.ListFields(featureclass, fieldname)

	fieldCount = len(fieldList)

	if (fieldCount == 1):
		return True
	else:
		return False



geographyLevels =[ {'level':'TRA','TRA_Name':'TRA_Name','fieldName':['TRA_Name','TRA_TYPE'],'match':'0','geographyLevel':99}]

chartTypes = [{'name':'TRA',
			   'table':'TRA',
			   'fields_conversion':uplift_Data,
			   'fields_dissovled': [['ALL_uplift', 'MEAN'],
			   						['Hab_uplift_WetlandsBMPs', 'MEAN'],
			   						['Hab_uplift_AvdConv','MEAN'],
			   						['Hab_uplift_AqCon', 'MEAN'],
			   						['Hab_uplift_Restoration','MEAN'],
			   						['Hab_uplift_norm','MEAN'],
									['Hydro_uplift_norm', 'MEAN'],
									['WQ_uplift_norm', 'MEAN']]
				}]


for chartType in chartTypes:
	print 'Chart Type: ' + chartType['name']
	chartTypeName = chartType['name']

	#NHDCat_comb_baseline_Layer = "NHDCat_comb_baseline"
	#NHDCat_comb_uplift_Layer = "NHDCat_comb_uplift"

	inputFC =  os.path.join(path, chartType['table'])

	#get fields in input data
	fields = arcpy.ListFields(  os.path.join(path, inputFC)  )

	#get json data for how to deal with each field
	input_dict = json.loads(chartType['fields_conversion'])


	for geog in geographyLevels:
		currentGeographyLevel = geog['TRA_Name']
		print 'Dissolve: ' + currentGeographyLevel
		print '  ' + geog['level']

		temp_dissolve = os.path.join(outGDBFull, geog['level'])
	 	dissolve = os.path.join(outGDBFull, 'dissolve')

		#if feature class exists delete
		if arcpy.Exists(temp_dissolve):
			arcpy.Delete_management(temp_dissolve)

		#dissolve on geographyLevels
		StatisticsFields = chartType['fields_dissovled']
		arcpy.Dissolve_management(inputFC, temp_dissolve, geog['fieldName'], StatisticsFields, "MULTI_PART", "DISSOLVE_LINES" )
		#"HUC_12 FIRST;ALL_base MEAN;Hab_base_norm MEAN;Hydro_base_norm MEAN;WQ_base_norm MEAN;MeanLikelihood_norm MEAN;q2yr_base_norm MEAN;q10yr_base_norm MEAN;q50yr_base_norm MEAN;q100yr_base_norm MEAN;N_total_base_norm MEAN;P_total_base_norm MEAN;N_AG_base_norm MEAN;N_URBAN_base_norm MEAN;N_CMAQ2002KG_base_norm MEAN;P_AG_base_norm MEAN;P_URBAN_base_norm MEAN", "MULTI_PART", "DISSOLVE_LINES")

		#iterate fields and to send dissolve
		for field in fields:

			#find matching instance of field on data.
			#then use this to construct the dissilove varriables.
			output_dict = [x for x in input_dict if x['fieldName'] == field.name]

			#if field exists in template we will use the field in output ddata.
			#  need to know who we want the table data formated - derieved from tempatle json
			if (output_dict):
				transposeField = output_dict[0]['fieldName']
				temp_transposed = os.path.join(outGDB, 'temp_transposed_' + currentGeographyLevel + '_'  + transposeField)

				#if feature class exists delete
				if arcpy.Exists(temp_transposed):
					arcpy.Delete_management(temp_transposed)

				arcpy.TransposeFields_management(temp_dissolve, "MEAN_" + transposeField +" MEAN_" + transposeField, temp_transposed, "chart_label", "chart_value",  geog['fieldName'])

				print '  ' + transposeField
				for f in output_dict[0]:
					print '    ' + f

				for field in transposedTemplate:
					fieldName = field['fieldname']
					fieldType = field['fieldType']
					fieldLength = field['Length']
					if not FieldExist(temp_transposed,fieldName):
						arcpy.AddField_management(temp_transposed, fieldName, fieldType, "", "", fieldLength, "", "NULLABLE", "NON_REQUIRED", "")


				# Process: calculate_geography_level
				arcpy.CalculateField_management(temp_transposed, "geography_level",   geog['geographyLevel'], "PYTHON", "")

				# Process: calculate_geography_match_id
				if  geog['level'] == 'Catchment':
					arcpy.CalculateField_management(temp_transposed, "geography_match_id",  "!"+ geog['match']+"!", "PYTHON", "")
				else:
					arcpy.CalculateField_management(temp_transposed, "geography_match_id", "!"+currentGeographyLevel+"![0:"+ geog['match']+"]", "PYTHON", "")

				arcpy.CalculateField_management(temp_transposed, "chart_description", "'" + output_dict[0]['chartDescription'] + "'", "PYTHON", "")

				# Process: Calculate_chart_type
				arcpy.CalculateField_management(temp_transposed, "chart_id","'" + output_dict[0]['chartId'] + "'" , "PYTHON", "")

				# Process: Calculate_chart_type
				arcpy.CalculateField_management(temp_transposed, "chart_matchid","'" + output_dict[0]['chartMatchId'] + "'" , "PYTHON", "")

				# Process: Calculate_chart_type
				arcpy.CalculateField_management(temp_transposed, "chart_type","'" + output_dict[0]['chartType'] + "'" , "PYTHON", "")

				# Process: Calculate_chart_level_label
				arcpy.CalculateField_management(temp_transposed, "chart_level_label", "'" + output_dict[0]['chartLabel'] + "'", "PYTHON", "")

				# Process: Calculate_chart_level
				arcpy.CalculateField_management(temp_transposed, "chart_level", "'" + output_dict[0]['chartLevel'] + "'", "PYTHON", "")

				arcpy.CalculateField_management(temp_transposed, "id", "!" + geog['TRA_Name'] + "!" , "PYTHON", "")

				# Process: Calculate_id
				arcpy.CalculateField_management(temp_transposed, "geography_label", """"TRA" +" " +  !TRA_TYPE!""", "PYTHON", "")

				#round to two decimealss
				arcpy.CalculateField_management(temp_transposed, "chart_value", "round(float(!chart_value!),8)", "PYTHON", "")

				if FieldExist(inputFC,currentGeographyLevel):
					deleteFields = []
					deleteFields.append( geog['fieldName'][1] )
					t = arcpy.DeleteField_management(temp_transposed, deleteFields)


				if FieldExist(inputFC,currentGeographyLevel):
					deleteFields = []
					deleteFields.append(currentGeographyLevel)
					t = arcpy.DeleteField_management(temp_transposed, deleteFields)

				#remove huc12
				if FieldExist(temp_transposed,'FIRST_HUC_12'):
					deleteFields = []
					deleteFields.append('FIRST_HUC_12')
					t = arcpy.DeleteField_management(temp_transposed, deleteFields)

				if FieldExist(temp_dissolve, "MEAN_" + transposeField):
					deleteFields =[]
					deleteFields.append( "MEAN_" + transposeField)
					arcpy.DeleteField_management(temp_dissolve, deleteFields)

				#append to transpose
				arcpy.Append_management(temp_transposed,transposed)

				#delete temp transpose
				if arcpy.Exists(temp_transposed):
					arcpy.Delete_management(temp_transposed)

for geog in geographyLevels:
	temp_dissolve = os.path.join(outGDBFull, geog['level'])

	if FieldExist(temp_dissolve, geog['fieldName'][0]):
		arcpy.AlterField_management(temp_dissolve,  geog['fieldName'][0], "id", "id", "", "", "NON_NULLABLE", "false")
		# arcpy.CalculateField_management(temp_transposed, geog['fieldName'][0], geog['fieldName'][0] + " " + geog['fieldName'][0], "PYTHON", "")


	if FieldExist(temp_dissolve, 'FIRST_HUC_12'):
		deleteFields =[]
		deleteFields.append('FIRST_HUC_12')
		arcpy.DeleteField_management(temp_dissolve, deleteFields)

#if huc_6 exists delete it
if FieldExist(inputFC,'HUC_6'):
	deleteFields = []
	deleteFields.append('HUC_6')
	t = arcpy.DeleteField_management(inputFC, deleteFields)


#process xwalk for tras to hucs
